package com.ims.core.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * InstituteBranch generated by hbm2java
 */
public class InstituteBranch implements java.io.Serializable {

	private Integer id;
	private Institute institute;
	private Set instituteBranchTenures = new HashSet(0);
	private Set instituteBranchModules = new HashSet(0);
	private Set instituteBranchAcademicPrograms = new HashSet(0);

	public InstituteBranch() {
	}

	public InstituteBranch(Institute institute) {
		this.institute = institute;
	}

	public InstituteBranch(Institute institute, Set instituteBranchTenures,
			Set instituteBranchModules, Set instituteBranchAcademicPrograms) {
		this.institute = institute;
		this.instituteBranchTenures = instituteBranchTenures;
		this.instituteBranchModules = instituteBranchModules;
		this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Institute getInstitute() {
		return this.institute;
	}

	public void setInstitute(Institute institute) {
		this.institute = institute;
	}

	public Set getInstituteBranchTenures() {
		return this.instituteBranchTenures;
	}

	public void setInstituteBranchTenures(Set instituteBranchTenures) {
		this.instituteBranchTenures = instituteBranchTenures;
	}

	public Set getInstituteBranchModules() {
		return this.instituteBranchModules;
	}

	public void setInstituteBranchModules(Set instituteBranchModules) {
		this.instituteBranchModules = instituteBranchModules;
	}

	public Set getInstituteBranchAcademicPrograms() {
		return this.instituteBranchAcademicPrograms;
	}

	public void setInstituteBranchAcademicPrograms(
			Set instituteBranchAcademicPrograms) {
		this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
	}

}
