package com.ims.dal.entities;
// Generated Dec 30, 2012 4:18:24 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusinessData generated by hbm2java
 */
@Entity
@Table(name="business_data"
    ,catalog="ims"
)
public class BusinessData  implements java.io.Serializable {


     private Long id;
     private BusinessDataReference businessDataReference;
     private UserRoleScreenElement userRoleScreenElement;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private String value;

    public BusinessData() {
    }

	
    public BusinessData(BusinessDataReference businessDataReference, UserRoleScreenElement userRoleScreenElement) {
        this.businessDataReference = businessDataReference;
        this.userRoleScreenElement = userRoleScreenElement;
    }
    public BusinessData(BusinessDataReference businessDataReference, UserRoleScreenElement userRoleScreenElement, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, String value) {
       this.businessDataReference = businessDataReference;
       this.userRoleScreenElement = userRoleScreenElement;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="business_data_reference_id", nullable=false)
    public BusinessDataReference getBusinessDataReference() {
        return this.businessDataReference;
    }
    
    public void setBusinessDataReference(BusinessDataReference businessDataReference) {
        this.businessDataReference = businessDataReference;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_role_screen_element_id", nullable=false)
    public UserRoleScreenElement getUserRoleScreenElement() {
        return this.userRoleScreenElement;
    }
    
    public void setUserRoleScreenElement(UserRoleScreenElement userRoleScreenElement) {
        this.userRoleScreenElement = userRoleScreenElement;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="created_by")
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="last_updated_by")
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    
    @Column(name="status", length=5)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="value")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


