package com.ims.dal.entities;
// Generated Dec 30, 2012 4:18:24 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstituteBranchTenure generated by hbm2java
 */
@Entity
@Table(name="institute_branch_tenure"
    ,catalog="ims"
)
public class InstituteBranchTenure  implements java.io.Serializable {


     private Long id;
     private Tenure tenure;
     private InstituteBranch instituteBranch;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<InstituteBranchTenureUser> instituteBranchTenureUsers = new HashSet<InstituteBranchTenureUser>(0);
     private Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses = new HashSet<TenureAcademicProgramCourse>(0);

    public InstituteBranchTenure() {
    }

	
    public InstituteBranchTenure(Tenure tenure, InstituteBranch instituteBranch) {
        this.tenure = tenure;
        this.instituteBranch = instituteBranch;
    }
    public InstituteBranchTenure(Tenure tenure, InstituteBranch instituteBranch, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<InstituteBranchTenureUser> instituteBranchTenureUsers, Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
       this.tenure = tenure;
       this.instituteBranch = instituteBranch;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.instituteBranchTenureUsers = instituteBranchTenureUsers;
       this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tenure_id", nullable=false)
    public Tenure getTenure() {
        return this.tenure;
    }
    
    public void setTenure(Tenure tenure) {
        this.tenure = tenure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="institute_branch_id", nullable=false)
    public InstituteBranch getInstituteBranch() {
        return this.instituteBranch;
    }
    
    public void setInstituteBranch(InstituteBranch instituteBranch) {
        this.instituteBranch = instituteBranch;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="created_by")
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated_date", length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="last_updated_by")
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    
    @Column(name="status", length=5)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="instituteBranchTenure")
    public Set<InstituteBranchTenureUser> getInstituteBranchTenureUsers() {
        return this.instituteBranchTenureUsers;
    }
    
    public void setInstituteBranchTenureUsers(Set<InstituteBranchTenureUser> instituteBranchTenureUsers) {
        this.instituteBranchTenureUsers = instituteBranchTenureUsers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="instituteBranchTenure")
    public Set<TenureAcademicProgramCourse> getTenureAcademicProgramCourses() {
        return this.tenureAcademicProgramCourses;
    }
    
    public void setTenureAcademicProgramCourses(Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
        this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
    }




}


