package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AcademicProgram generated by hbm2java
 */
public class AcademicProgram  implements java.io.Serializable {


     private Long id;
     private Academic academic;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<InstituteBranchAcademicProgram> instituteBranchAcademicPrograms = new HashSet<InstituteBranchAcademicProgram>(0);
     private Set<AcademicProgramCourse> academicProgramCourses = new HashSet<AcademicProgramCourse>(0);

    public AcademicProgram() {
    }

	
    public AcademicProgram(Academic academic) {
        this.academic = academic;
    }
    public AcademicProgram(Academic academic, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<InstituteBranchAcademicProgram> instituteBranchAcademicPrograms, Set<AcademicProgramCourse> academicProgramCourses) {
       this.academic = academic;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
       this.academicProgramCourses = academicProgramCourses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Academic getAcademic() {
        return this.academic;
    }
    
    public void setAcademic(Academic academic) {
        this.academic = academic;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<InstituteBranchAcademicProgram> getInstituteBranchAcademicPrograms() {
        return this.instituteBranchAcademicPrograms;
    }
    
    public void setInstituteBranchAcademicPrograms(Set<InstituteBranchAcademicProgram> instituteBranchAcademicPrograms) {
        this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
    }
    public Set<AcademicProgramCourse> getAcademicProgramCourses() {
        return this.academicProgramCourses;
    }
    
    public void setAcademicProgramCourses(Set<AcademicProgramCourse> academicProgramCourses) {
        this.academicProgramCourses = academicProgramCourses;
    }




}


