package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AcademicProgramCourse generated by hbm2java
 */
public class AcademicProgramCourse  implements java.io.Serializable {


     private Long id;
     private Course course;
     private AcademicProgram academicProgram;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses = new HashSet<TenureAcademicProgramCourse>(0);

    public AcademicProgramCourse() {
    }

	
    public AcademicProgramCourse(Course course, AcademicProgram academicProgram) {
        this.course = course;
        this.academicProgram = academicProgram;
    }
    public AcademicProgramCourse(Course course, AcademicProgram academicProgram, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
       this.course = course;
       this.academicProgram = academicProgram;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public AcademicProgram getAcademicProgram() {
        return this.academicProgram;
    }
    
    public void setAcademicProgram(AcademicProgram academicProgram) {
        this.academicProgram = academicProgram;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<TenureAcademicProgramCourse> getTenureAcademicProgramCourses() {
        return this.tenureAcademicProgramCourses;
    }
    
    public void setTenureAcademicProgramCourses(Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
        this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
    }




}


