package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Collection generated by hbm2java
 */
public class Collection  implements java.io.Serializable {


     private Long id;
     private DurationType durationType;
     private InstituteBranchTenureUser instituteBranchTenureUser;
     private CollectionSetupData collectionSetupData;
     private CollectionMode collectionMode;
     private CollectionStatus collectionStatus;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Collection() {
    }

	
    public Collection(DurationType durationType, InstituteBranchTenureUser instituteBranchTenureUser, CollectionSetupData collectionSetupData, CollectionMode collectionMode, CollectionStatus collectionStatus) {
        this.durationType = durationType;
        this.instituteBranchTenureUser = instituteBranchTenureUser;
        this.collectionSetupData = collectionSetupData;
        this.collectionMode = collectionMode;
        this.collectionStatus = collectionStatus;
    }
    public Collection(DurationType durationType, InstituteBranchTenureUser instituteBranchTenureUser, CollectionSetupData collectionSetupData, CollectionMode collectionMode, CollectionStatus collectionStatus, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<Transaction> transactions) {
       this.durationType = durationType;
       this.instituteBranchTenureUser = instituteBranchTenureUser;
       this.collectionSetupData = collectionSetupData;
       this.collectionMode = collectionMode;
       this.collectionStatus = collectionStatus;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.transactions = transactions;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public DurationType getDurationType() {
        return this.durationType;
    }
    
    public void setDurationType(DurationType durationType) {
        this.durationType = durationType;
    }
    public InstituteBranchTenureUser getInstituteBranchTenureUser() {
        return this.instituteBranchTenureUser;
    }
    
    public void setInstituteBranchTenureUser(InstituteBranchTenureUser instituteBranchTenureUser) {
        this.instituteBranchTenureUser = instituteBranchTenureUser;
    }
    public CollectionSetupData getCollectionSetupData() {
        return this.collectionSetupData;
    }
    
    public void setCollectionSetupData(CollectionSetupData collectionSetupData) {
        this.collectionSetupData = collectionSetupData;
    }
    public CollectionMode getCollectionMode() {
        return this.collectionMode;
    }
    
    public void setCollectionMode(CollectionMode collectionMode) {
        this.collectionMode = collectionMode;
    }
    public CollectionStatus getCollectionStatus() {
        return this.collectionStatus;
    }
    
    public void setCollectionStatus(CollectionStatus collectionStatus) {
        this.collectionStatus = collectionStatus;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


