package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InstituteBranchTenure generated by hbm2java
 */
public class InstituteBranchTenure  implements java.io.Serializable {


     private Long id;
     private Tenure tenure;
     private InstituteBranch instituteBranch;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<InstituteBranchTenureUser> instituteBranchTenureUsers = new HashSet<InstituteBranchTenureUser>(0);
     private Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses = new HashSet<TenureAcademicProgramCourse>(0);

    public InstituteBranchTenure() {
    }

	
    public InstituteBranchTenure(Tenure tenure, InstituteBranch instituteBranch) {
        this.tenure = tenure;
        this.instituteBranch = instituteBranch;
    }
    public InstituteBranchTenure(Tenure tenure, InstituteBranch instituteBranch, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<InstituteBranchTenureUser> instituteBranchTenureUsers, Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
       this.tenure = tenure;
       this.instituteBranch = instituteBranch;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.instituteBranchTenureUsers = instituteBranchTenureUsers;
       this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Tenure getTenure() {
        return this.tenure;
    }
    
    public void setTenure(Tenure tenure) {
        this.tenure = tenure;
    }
    public InstituteBranch getInstituteBranch() {
        return this.instituteBranch;
    }
    
    public void setInstituteBranch(InstituteBranch instituteBranch) {
        this.instituteBranch = instituteBranch;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<InstituteBranchTenureUser> getInstituteBranchTenureUsers() {
        return this.instituteBranchTenureUsers;
    }
    
    public void setInstituteBranchTenureUsers(Set<InstituteBranchTenureUser> instituteBranchTenureUsers) {
        this.instituteBranchTenureUsers = instituteBranchTenureUsers;
    }
    public Set<TenureAcademicProgramCourse> getTenureAcademicProgramCourses() {
        return this.tenureAcademicProgramCourses;
    }
    
    public void setTenureAcademicProgramCourses(Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
        this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
    }




}


