package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InstituteBranchTenureUser generated by hbm2java
 */
public class InstituteBranchTenureUser  implements java.io.Serializable {


     private Long id;
     private User user;
     private InstituteBranchTenure instituteBranchTenure;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<InstituteBranchUserAcademicProgram> instituteBranchUserAcademicPrograms = new HashSet<InstituteBranchUserAcademicProgram>(0);
     private Set<Collection> collections = new HashSet<Collection>(0);
     private Set<UserRoleInstituteBranchModule> userRoleInstituteBranchModules = new HashSet<UserRoleInstituteBranchModule>(0);

    public InstituteBranchTenureUser() {
    }

	
    public InstituteBranchTenureUser(User user, InstituteBranchTenure instituteBranchTenure) {
        this.user = user;
        this.instituteBranchTenure = instituteBranchTenure;
    }
    public InstituteBranchTenureUser(User user, InstituteBranchTenure instituteBranchTenure, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<InstituteBranchUserAcademicProgram> instituteBranchUserAcademicPrograms, Set<Collection> collections, Set<UserRoleInstituteBranchModule> userRoleInstituteBranchModules) {
       this.user = user;
       this.instituteBranchTenure = instituteBranchTenure;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
       this.collections = collections;
       this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public InstituteBranchTenure getInstituteBranchTenure() {
        return this.instituteBranchTenure;
    }
    
    public void setInstituteBranchTenure(InstituteBranchTenure instituteBranchTenure) {
        this.instituteBranchTenure = instituteBranchTenure;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<InstituteBranchUserAcademicProgram> getInstituteBranchUserAcademicPrograms() {
        return this.instituteBranchUserAcademicPrograms;
    }
    
    public void setInstituteBranchUserAcademicPrograms(Set<InstituteBranchUserAcademicProgram> instituteBranchUserAcademicPrograms) {
        this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
    }
    public Set<Collection> getCollections() {
        return this.collections;
    }
    
    public void setCollections(Set<Collection> collections) {
        this.collections = collections;
    }
    public Set<UserRoleInstituteBranchModule> getUserRoleInstituteBranchModules() {
        return this.userRoleInstituteBranchModules;
    }
    
    public void setUserRoleInstituteBranchModules(Set<UserRoleInstituteBranchModule> userRoleInstituteBranchModules) {
        this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
    }




}


