package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InstituteBranch generated by hbm2java
 */
public class InstituteBranch  implements java.io.Serializable {


     private Long id;
     private Institute institute;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<InstituteBranchModule> instituteBranchModules = new HashSet<InstituteBranchModule>(0);
     private Set<InstituteBranchAcademicProgram> instituteBranchAcademicPrograms = new HashSet<InstituteBranchAcademicProgram>(0);
     private Set<InstituteBranchTenure> instituteBranchTenures = new HashSet<InstituteBranchTenure>(0);

    public InstituteBranch() {
    }

	
    public InstituteBranch(Institute institute) {
        this.institute = institute;
    }
    public InstituteBranch(Institute institute, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<InstituteBranchModule> instituteBranchModules, Set<InstituteBranchAcademicProgram> instituteBranchAcademicPrograms, Set<InstituteBranchTenure> instituteBranchTenures) {
       this.institute = institute;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.instituteBranchModules = instituteBranchModules;
       this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
       this.instituteBranchTenures = instituteBranchTenures;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<InstituteBranchModule> getInstituteBranchModules() {
        return this.instituteBranchModules;
    }
    
    public void setInstituteBranchModules(Set<InstituteBranchModule> instituteBranchModules) {
        this.instituteBranchModules = instituteBranchModules;
    }
    public Set<InstituteBranchAcademicProgram> getInstituteBranchAcademicPrograms() {
        return this.instituteBranchAcademicPrograms;
    }
    
    public void setInstituteBranchAcademicPrograms(Set<InstituteBranchAcademicProgram> instituteBranchAcademicPrograms) {
        this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
    }
    public Set<InstituteBranchTenure> getInstituteBranchTenures() {
        return this.instituteBranchTenures;
    }
    
    public void setInstituteBranchTenures(Set<InstituteBranchTenure> instituteBranchTenures) {
        this.instituteBranchTenures = instituteBranchTenures;
    }




}


