package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InstituteBranchModule generated by hbm2java
 */
public class InstituteBranchModule  implements java.io.Serializable {


     private Long id;
     private Module module;
     private InstituteBranch instituteBranch;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<RoleInstituteBranchModule> roleInstituteBranchModules = new HashSet<RoleInstituteBranchModule>(0);

    public InstituteBranchModule() {
    }

	
    public InstituteBranchModule(Module module, InstituteBranch instituteBranch) {
        this.module = module;
        this.instituteBranch = instituteBranch;
    }
    public InstituteBranchModule(Module module, InstituteBranch instituteBranch, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<RoleInstituteBranchModule> roleInstituteBranchModules) {
       this.module = module;
       this.instituteBranch = instituteBranch;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.roleInstituteBranchModules = roleInstituteBranchModules;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }
    public InstituteBranch getInstituteBranch() {
        return this.instituteBranch;
    }
    
    public void setInstituteBranch(InstituteBranch instituteBranch) {
        this.instituteBranch = instituteBranch;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<RoleInstituteBranchModule> getRoleInstituteBranchModules() {
        return this.roleInstituteBranchModules;
    }
    
    public void setRoleInstituteBranchModules(Set<RoleInstituteBranchModule> roleInstituteBranchModules) {
        this.roleInstituteBranchModules = roleInstituteBranchModules;
    }




}


