package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ModuleScreenElement generated by hbm2java
 */
public class ModuleScreenElement  implements java.io.Serializable {


     private Long id;
     private BusinessFields businessFields;
     private ModuleScreen moduleScreen;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<UserRoleScreenElement> userRoleScreenElements = new HashSet<UserRoleScreenElement>(0);

    public ModuleScreenElement() {
    }

	
    public ModuleScreenElement(BusinessFields businessFields, ModuleScreen moduleScreen) {
        this.businessFields = businessFields;
        this.moduleScreen = moduleScreen;
    }
    public ModuleScreenElement(BusinessFields businessFields, ModuleScreen moduleScreen, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<UserRoleScreenElement> userRoleScreenElements) {
       this.businessFields = businessFields;
       this.moduleScreen = moduleScreen;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.userRoleScreenElements = userRoleScreenElements;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public BusinessFields getBusinessFields() {
        return this.businessFields;
    }
    
    public void setBusinessFields(BusinessFields businessFields) {
        this.businessFields = businessFields;
    }
    public ModuleScreen getModuleScreen() {
        return this.moduleScreen;
    }
    
    public void setModuleScreen(ModuleScreen moduleScreen) {
        this.moduleScreen = moduleScreen;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<UserRoleScreenElement> getUserRoleScreenElements() {
        return this.userRoleScreenElements;
    }
    
    public void setUserRoleScreenElements(Set<UserRoleScreenElement> userRoleScreenElements) {
        this.userRoleScreenElements = userRoleScreenElements;
    }




}


