package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RoleInstituteBranchModule generated by hbm2java
 */
public class RoleInstituteBranchModule  implements java.io.Serializable {


     private Long id;
     private Role role;
     private InstituteBranchModule instituteBranchModule;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<UserRoleInstituteBranchModule> userRoleInstituteBranchModules = new HashSet<UserRoleInstituteBranchModule>(0);

    public RoleInstituteBranchModule() {
    }

	
    public RoleInstituteBranchModule(Role role, InstituteBranchModule instituteBranchModule) {
        this.role = role;
        this.instituteBranchModule = instituteBranchModule;
    }
    public RoleInstituteBranchModule(Role role, InstituteBranchModule instituteBranchModule, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<UserRoleInstituteBranchModule> userRoleInstituteBranchModules) {
       this.role = role;
       this.instituteBranchModule = instituteBranchModule;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public InstituteBranchModule getInstituteBranchModule() {
        return this.instituteBranchModule;
    }
    
    public void setInstituteBranchModule(InstituteBranchModule instituteBranchModule) {
        this.instituteBranchModule = instituteBranchModule;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<UserRoleInstituteBranchModule> getUserRoleInstituteBranchModules() {
        return this.userRoleInstituteBranchModules;
    }
    
    public void setUserRoleInstituteBranchModules(Set<UserRoleInstituteBranchModule> userRoleInstituteBranchModules) {
        this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
    }




}


