package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TenureAcademicProgramCourse generated by hbm2java
 */
public class TenureAcademicProgramCourse  implements java.io.Serializable {


     private Long id;
     private InstituteBranchTenure instituteBranchTenure;
     private AcademicProgramCourse academicProgramCourse;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<InstituteBranchUserAcademicProgram> instituteBranchUserAcademicPrograms = new HashSet<InstituteBranchUserAcademicProgram>(0);

    public TenureAcademicProgramCourse() {
    }

	
    public TenureAcademicProgramCourse(InstituteBranchTenure instituteBranchTenure, AcademicProgramCourse academicProgramCourse) {
        this.instituteBranchTenure = instituteBranchTenure;
        this.academicProgramCourse = academicProgramCourse;
    }
    public TenureAcademicProgramCourse(InstituteBranchTenure instituteBranchTenure, AcademicProgramCourse academicProgramCourse, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<InstituteBranchUserAcademicProgram> instituteBranchUserAcademicPrograms) {
       this.instituteBranchTenure = instituteBranchTenure;
       this.academicProgramCourse = academicProgramCourse;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public InstituteBranchTenure getInstituteBranchTenure() {
        return this.instituteBranchTenure;
    }
    
    public void setInstituteBranchTenure(InstituteBranchTenure instituteBranchTenure) {
        this.instituteBranchTenure = instituteBranchTenure;
    }
    public AcademicProgramCourse getAcademicProgramCourse() {
        return this.academicProgramCourse;
    }
    
    public void setAcademicProgramCourse(AcademicProgramCourse academicProgramCourse) {
        this.academicProgramCourse = academicProgramCourse;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<InstituteBranchUserAcademicProgram> getInstituteBranchUserAcademicPrograms() {
        return this.instituteBranchUserAcademicPrograms;
    }
    
    public void setInstituteBranchUserAcademicPrograms(Set<InstituteBranchUserAcademicProgram> instituteBranchUserAcademicPrograms) {
        this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
    }




}


