package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserRoleScreenElement generated by hbm2java
 */
public class UserRoleScreenElement  implements java.io.Serializable {


     private Long id;
     private UserRoleInstituteBranchModule userRoleInstituteBranchModule;
     private Permission permission;
     private Rule rule;
     private ModuleScreenElement moduleScreenElement;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<UserProfile> userProfiles = new HashSet<UserProfile>(0);
     private Set<BusinessData> businessDatas = new HashSet<BusinessData>(0);

    public UserRoleScreenElement() {
    }

	
    public UserRoleScreenElement(UserRoleInstituteBranchModule userRoleInstituteBranchModule, Permission permission, Rule rule, ModuleScreenElement moduleScreenElement) {
        this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
        this.permission = permission;
        this.rule = rule;
        this.moduleScreenElement = moduleScreenElement;
    }
    public UserRoleScreenElement(UserRoleInstituteBranchModule userRoleInstituteBranchModule, Permission permission, Rule rule, ModuleScreenElement moduleScreenElement, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<UserProfile> userProfiles, Set<BusinessData> businessDatas) {
       this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
       this.permission = permission;
       this.rule = rule;
       this.moduleScreenElement = moduleScreenElement;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.userProfiles = userProfiles;
       this.businessDatas = businessDatas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public UserRoleInstituteBranchModule getUserRoleInstituteBranchModule() {
        return this.userRoleInstituteBranchModule;
    }
    
    public void setUserRoleInstituteBranchModule(UserRoleInstituteBranchModule userRoleInstituteBranchModule) {
        this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
    }
    public Permission getPermission() {
        return this.permission;
    }
    
    public void setPermission(Permission permission) {
        this.permission = permission;
    }
    public Rule getRule() {
        return this.rule;
    }
    
    public void setRule(Rule rule) {
        this.rule = rule;
    }
    public ModuleScreenElement getModuleScreenElement() {
        return this.moduleScreenElement;
    }
    
    public void setModuleScreenElement(ModuleScreenElement moduleScreenElement) {
        this.moduleScreenElement = moduleScreenElement;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<UserProfile> getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set<UserProfile> userProfiles) {
        this.userProfiles = userProfiles;
    }
    public Set<BusinessData> getBusinessDatas() {
        return this.businessDatas;
    }
    
    public void setBusinessDatas(Set<BusinessData> businessDatas) {
        this.businessDatas = businessDatas;
    }




}


