package com.ims.dal.vo;
// Generated Dec 30, 2012 4:18:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserRoleInstituteBranchModule generated by hbm2java
 */
public class UserRoleInstituteBranchModule  implements java.io.Serializable {


     private Long id;
     private RoleInstituteBranchModule roleInstituteBranchModule;
     private InstituteBranchTenureUser instituteBranchTenureUser;
     private Date createdDate;
     private Long createdBy;
     private Date lastUpdatedDate;
     private Long lastUpdatedBy;
     private String status;
     private Set<UserRoleScreenElement> userRoleScreenElements = new HashSet<UserRoleScreenElement>(0);

    public UserRoleInstituteBranchModule() {
    }

	
    public UserRoleInstituteBranchModule(RoleInstituteBranchModule roleInstituteBranchModule, InstituteBranchTenureUser instituteBranchTenureUser) {
        this.roleInstituteBranchModule = roleInstituteBranchModule;
        this.instituteBranchTenureUser = instituteBranchTenureUser;
    }
    public UserRoleInstituteBranchModule(RoleInstituteBranchModule roleInstituteBranchModule, InstituteBranchTenureUser instituteBranchTenureUser, Date createdDate, Long createdBy, Date lastUpdatedDate, Long lastUpdatedBy, String status, Set<UserRoleScreenElement> userRoleScreenElements) {
       this.roleInstituteBranchModule = roleInstituteBranchModule;
       this.instituteBranchTenureUser = instituteBranchTenureUser;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.status = status;
       this.userRoleScreenElements = userRoleScreenElements;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public RoleInstituteBranchModule getRoleInstituteBranchModule() {
        return this.roleInstituteBranchModule;
    }
    
    public void setRoleInstituteBranchModule(RoleInstituteBranchModule roleInstituteBranchModule) {
        this.roleInstituteBranchModule = roleInstituteBranchModule;
    }
    public InstituteBranchTenureUser getInstituteBranchTenureUser() {
        return this.instituteBranchTenureUser;
    }
    
    public void setInstituteBranchTenureUser(InstituteBranchTenureUser instituteBranchTenureUser) {
        this.instituteBranchTenureUser = instituteBranchTenureUser;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<UserRoleScreenElement> getUserRoleScreenElements() {
        return this.userRoleScreenElements;
    }
    
    public void setUserRoleScreenElements(Set<UserRoleScreenElement> userRoleScreenElements) {
        this.userRoleScreenElements = userRoleScreenElements;
    }




}


