package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * BusinessData generated by hbm2java
 */
public class BusinessData implements java.io.Serializable {

	private Integer id;
	private BusinessDataReference businessDataReference;
	private UserRoleScreenElement userRoleScreenElement;
	private String value;

	public BusinessData() {
	}

	public BusinessData(BusinessDataReference businessDataReference,
			UserRoleScreenElement userRoleScreenElement) {
		this.businessDataReference = businessDataReference;
		this.userRoleScreenElement = userRoleScreenElement;
	}

	public BusinessData(BusinessDataReference businessDataReference,
			UserRoleScreenElement userRoleScreenElement, String value) {
		this.businessDataReference = businessDataReference;
		this.userRoleScreenElement = userRoleScreenElement;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BusinessDataReference getBusinessDataReference() {
		return this.businessDataReference;
	}

	public void setBusinessDataReference(
			BusinessDataReference businessDataReference) {
		this.businessDataReference = businessDataReference;
	}

	public UserRoleScreenElement getUserRoleScreenElement() {
		return this.userRoleScreenElement;
	}

	public void setUserRoleScreenElement(
			UserRoleScreenElement userRoleScreenElement) {
		this.userRoleScreenElement = userRoleScreenElement;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
