package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * BusinessFields generated by hbm2java
 */
public class BusinessFields implements java.io.Serializable {

	private Integer id;
	private Set moduleScreenElements = new HashSet(0);

	public BusinessFields() {
	}

	public BusinessFields(Set moduleScreenElements) {
		this.moduleScreenElements = moduleScreenElements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getModuleScreenElements() {
		return this.moduleScreenElements;
	}

	public void setModuleScreenElements(Set moduleScreenElements) {
		this.moduleScreenElements = moduleScreenElements;
	}

}
