package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.ims.core.dal.bean.InstituteBranchTenure;

/**
 * InstituteBranchTenureUser generated by hbm2java
 */
@Entity
@Table(name = "Institute_Branch_Tenure_User", catalog = "ims2")
public class InstituteBranchTenureUser implements java.io.Serializable {

	private Integer id;
	private InstituteBranchTenure instituteBranchTenure;
	private Users users;
	private Set userRoleInstituteBranchModules = new HashSet(0);
	private Set instituteBranchUserAcademicPrograms = new HashSet(0);
	private Set collections = new HashSet(0);

	public InstituteBranchTenureUser() {
	}

	public InstituteBranchTenureUser(
			InstituteBranchTenure instituteBranchTenure, Users users) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.users = users;
	}

	public InstituteBranchTenureUser(
			InstituteBranchTenure instituteBranchTenure, Users users,
			Set userRoleInstituteBranchModules,
			Set instituteBranchUserAcademicPrograms, Set collections) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.users = users;
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
		this.collections = collections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Institute_Branch_Tenure_id", nullable = false)
	public InstituteBranchTenure getInstituteBranchTenure() {
		return this.instituteBranchTenure;
	}

	public void setInstituteBranchTenure(
			InstituteBranchTenure instituteBranchTenure) {
		this.instituteBranchTenure = instituteBranchTenure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instituteBranchTenureUser")
	public Set getUserRoleInstituteBranchModules() {
		return this.userRoleInstituteBranchModules;
	}

	public void setUserRoleInstituteBranchModules(
			Set userRoleInstituteBranchModules) {
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instituteBranchTenureUser")
	public Set getInstituteBranchUserAcademicPrograms() {
		return this.instituteBranchUserAcademicPrograms;
	}

	public void setInstituteBranchUserAcademicPrograms(
			Set instituteBranchUserAcademicPrograms) {
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instituteBranchTenureUser")
	public Set getCollections() {
		return this.collections;
	}

	public void setCollections(Set collections) {
		this.collections = collections;
	}

}
