package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.ims.core.dal.bean.InstituteBranchTenure;

/**
 * InstituteBranchTenureUser generated by hbm2java
 */
public class InstituteBranchTenureUser implements java.io.Serializable {

	private Integer id;
	private InstituteBranchTenure instituteBranchTenure;
	private Users users;
	private Set userRoleInstituteBranchModules = new HashSet(0);
	private Set instituteBranchUserAcademicPrograms = new HashSet(0);
	private Set collections = new HashSet(0);

	public InstituteBranchTenureUser() {
	}

	public InstituteBranchTenureUser(
			InstituteBranchTenure instituteBranchTenure, Users users) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.users = users;
	}

	public InstituteBranchTenureUser(
			InstituteBranchTenure instituteBranchTenure, Users users,
			Set userRoleInstituteBranchModules,
			Set instituteBranchUserAcademicPrograms, Set collections) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.users = users;
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
		this.collections = collections;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public InstituteBranchTenure getInstituteBranchTenure() {
		return this.instituteBranchTenure;
	}

	public void setInstituteBranchTenure(
			InstituteBranchTenure instituteBranchTenure) {
		this.instituteBranchTenure = instituteBranchTenure;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Set getUserRoleInstituteBranchModules() {
		return this.userRoleInstituteBranchModules;
	}

	public void setUserRoleInstituteBranchModules(
			Set userRoleInstituteBranchModules) {
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
	}

	public Set getInstituteBranchUserAcademicPrograms() {
		return this.instituteBranchUserAcademicPrograms;
	}

	public void setInstituteBranchUserAcademicPrograms(
			Set instituteBranchUserAcademicPrograms) {
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
	}

	public Set getCollections() {
		return this.collections;
	}

	public void setCollections(Set collections) {
		this.collections = collections;
	}

}
