package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module implements java.io.Serializable {

	private Integer id;
	private Set moduleScreens = new HashSet(0);
	private Set instituteBranchModules = new HashSet(0);

	public Module() {
	}

	public Module(Set moduleScreens, Set instituteBranchModules) {
		this.moduleScreens = moduleScreens;
		this.instituteBranchModules = instituteBranchModules;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getModuleScreens() {
		return this.moduleScreens;
	}

	public void setModuleScreens(Set moduleScreens) {
		this.moduleScreens = moduleScreens;
	}

	public Set getInstituteBranchModules() {
		return this.instituteBranchModules;
	}

	public void setInstituteBranchModules(Set instituteBranchModules) {
		this.instituteBranchModules = instituteBranchModules;
	}

}
