package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ModuleScreenElement generated by hbm2java
 */
public class ModuleScreenElement implements java.io.Serializable {

	private Integer id;
	private BusinessFields businessFields;
	private ModuleScreen moduleScreen;
	private Set userRoleScreenElements = new HashSet(0);

	public ModuleScreenElement() {
	}

	public ModuleScreenElement(BusinessFields businessFields,
			ModuleScreen moduleScreen) {
		this.businessFields = businessFields;
		this.moduleScreen = moduleScreen;
	}

	public ModuleScreenElement(BusinessFields businessFields,
			ModuleScreen moduleScreen, Set userRoleScreenElements) {
		this.businessFields = businessFields;
		this.moduleScreen = moduleScreen;
		this.userRoleScreenElements = userRoleScreenElements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BusinessFields getBusinessFields() {
		return this.businessFields;
	}

	public void setBusinessFields(BusinessFields businessFields) {
		this.businessFields = businessFields;
	}

	public ModuleScreen getModuleScreen() {
		return this.moduleScreen;
	}

	public void setModuleScreen(ModuleScreen moduleScreen) {
		this.moduleScreen = moduleScreen;
	}

	public Set getUserRoleScreenElements() {
		return this.userRoleScreenElements;
	}

	public void setUserRoleScreenElements(Set userRoleScreenElements) {
		this.userRoleScreenElements = userRoleScreenElements;
	}

}
