package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ModuleScreen generated by hbm2java
 */
public class ModuleScreen implements java.io.Serializable {

	private Integer id;
	private Module module;
	private Set moduleScreenElements = new HashSet(0);

	public ModuleScreen() {
	}

	public ModuleScreen(Module module) {
		this.module = module;
	}

	public ModuleScreen(Module module, Set moduleScreenElements) {
		this.module = module;
		this.moduleScreenElements = moduleScreenElements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public Set getModuleScreenElements() {
		return this.moduleScreenElements;
	}

	public void setModuleScreenElements(Set moduleScreenElements) {
		this.moduleScreenElements = moduleScreenElements;
	}

}
