package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RoleInstituteBranchModule generated by hbm2java
 */
public class RoleInstituteBranchModule implements java.io.Serializable {

	private Integer id;
	private Role role;
	private InstituteBranchModule instituteBranchModule;
	private Set userRoleInstituteBranchModules = new HashSet(0);

	public RoleInstituteBranchModule() {
	}

	public RoleInstituteBranchModule(Role role,
			InstituteBranchModule instituteBranchModule) {
		this.role = role;
		this.instituteBranchModule = instituteBranchModule;
	}

	public RoleInstituteBranchModule(Role role,
			InstituteBranchModule instituteBranchModule,
			Set userRoleInstituteBranchModules) {
		this.role = role;
		this.instituteBranchModule = instituteBranchModule;
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public InstituteBranchModule getInstituteBranchModule() {
		return this.instituteBranchModule;
	}

	public void setInstituteBranchModule(
			InstituteBranchModule instituteBranchModule) {
		this.instituteBranchModule = instituteBranchModule;
	}

	public Set getUserRoleInstituteBranchModules() {
		return this.userRoleInstituteBranchModules;
	}

	public void setUserRoleInstituteBranchModules(
			Set userRoleInstituteBranchModules) {
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
	}

}
