package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private RoleType roleType;
	private Set roleInstituteBranchModules = new HashSet(0);

	public Role() {
	}

	public Role(RoleType roleType) {
		this.roleType = roleType;
	}

	public Role(RoleType roleType, Set roleInstituteBranchModules) {
		this.roleType = roleType;
		this.roleInstituteBranchModules = roleInstituteBranchModules;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	public Set getRoleInstituteBranchModules() {
		return this.roleInstituteBranchModules;
	}

	public void setRoleInstituteBranchModules(Set roleInstituteBranchModules) {
		this.roleInstituteBranchModules = roleInstituteBranchModules;
	}

}
