package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRoleInstituteBranchModule generated by hbm2java
 */
@Entity
@Table(name = "User_Role_Institute_Branch_Module", catalog = "ims2")
public class UserRoleInstituteBranchModule implements java.io.Serializable {

	private Integer id;
	private RoleInstituteBranchModule roleInstituteBranchModule;
	private InstituteBranchTenureUser instituteBranchTenureUser;
	private Set userRoleScreenElements = new HashSet(0);

	public UserRoleInstituteBranchModule() {
	}

	public UserRoleInstituteBranchModule(
			RoleInstituteBranchModule roleInstituteBranchModule,
			InstituteBranchTenureUser instituteBranchTenureUser) {
		this.roleInstituteBranchModule = roleInstituteBranchModule;
		this.instituteBranchTenureUser = instituteBranchTenureUser;
	}

	public UserRoleInstituteBranchModule(
			RoleInstituteBranchModule roleInstituteBranchModule,
			InstituteBranchTenureUser instituteBranchTenureUser,
			Set userRoleScreenElements) {
		this.roleInstituteBranchModule = roleInstituteBranchModule;
		this.instituteBranchTenureUser = instituteBranchTenureUser;
		this.userRoleScreenElements = userRoleScreenElements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Role_Institute_Branch_Module_id", nullable = false)
	public RoleInstituteBranchModule getRoleInstituteBranchModule() {
		return this.roleInstituteBranchModule;
	}

	public void setRoleInstituteBranchModule(
			RoleInstituteBranchModule roleInstituteBranchModule) {
		this.roleInstituteBranchModule = roleInstituteBranchModule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Institute_Branch_Tenure_User_id", nullable = false)
	public InstituteBranchTenureUser getInstituteBranchTenureUser() {
		return this.instituteBranchTenureUser;
	}

	public void setInstituteBranchTenureUser(
			InstituteBranchTenureUser instituteBranchTenureUser) {
		this.instituteBranchTenureUser = instituteBranchTenureUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoleInstituteBranchModule")
	public Set getUserRoleScreenElements() {
		return this.userRoleScreenElements;
	}

	public void setUserRoleScreenElements(Set userRoleScreenElements) {
		this.userRoleScreenElements = userRoleScreenElements;
	}

}
