package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserRoleScreenElement generated by hbm2java
 */
public class UserRoleScreenElement implements java.io.Serializable {

	private Integer id;
	private UserRoleInstituteBranchModule userRoleInstituteBranchModule;
	private Permission permission;
	private Rule rule;
	private ModuleScreenElement moduleScreenElement;
	private Set userProfiles = new HashSet(0);
	private Set businessDatas = new HashSet(0);

	public UserRoleScreenElement() {
	}

	public UserRoleScreenElement(
			UserRoleInstituteBranchModule userRoleInstituteBranchModule,
			Permission permission, Rule rule,
			ModuleScreenElement moduleScreenElement) {
		this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
		this.permission = permission;
		this.rule = rule;
		this.moduleScreenElement = moduleScreenElement;
	}

	public UserRoleScreenElement(
			UserRoleInstituteBranchModule userRoleInstituteBranchModule,
			Permission permission, Rule rule,
			ModuleScreenElement moduleScreenElement, Set userProfiles,
			Set businessDatas) {
		this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
		this.permission = permission;
		this.rule = rule;
		this.moduleScreenElement = moduleScreenElement;
		this.userProfiles = userProfiles;
		this.businessDatas = businessDatas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserRoleInstituteBranchModule getUserRoleInstituteBranchModule() {
		return this.userRoleInstituteBranchModule;
	}

	public void setUserRoleInstituteBranchModule(
			UserRoleInstituteBranchModule userRoleInstituteBranchModule) {
		this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
	}

	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	public Rule getRule() {
		return this.rule;
	}

	public void setRule(Rule rule) {
		this.rule = rule;
	}

	public ModuleScreenElement getModuleScreenElement() {
		return this.moduleScreenElement;
	}

	public void setModuleScreenElement(ModuleScreenElement moduleScreenElement) {
		this.moduleScreenElement = moduleScreenElement;
	}

	public Set getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set userProfiles) {
		this.userProfiles = userProfiles;
	}

	public Set getBusinessDatas() {
		return this.businessDatas;
	}

	public void setBusinessDatas(Set businessDatas) {
		this.businessDatas = businessDatas;
	}

}
