package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserRoleInstituteBranchModule generated by hbm2java
 */
public class UserRoleInstituteBranchModule implements java.io.Serializable {

	private Integer id;
	private RoleInstituteBranchModule roleInstituteBranchModule;
	private InstituteBranchTenureUser instituteBranchTenureUser;
	private Set userRoleScreenElements = new HashSet(0);

	public UserRoleInstituteBranchModule() {
	}

	public UserRoleInstituteBranchModule(
			RoleInstituteBranchModule roleInstituteBranchModule,
			InstituteBranchTenureUser instituteBranchTenureUser) {
		this.roleInstituteBranchModule = roleInstituteBranchModule;
		this.instituteBranchTenureUser = instituteBranchTenureUser;
	}

	public UserRoleInstituteBranchModule(
			RoleInstituteBranchModule roleInstituteBranchModule,
			InstituteBranchTenureUser instituteBranchTenureUser,
			Set userRoleScreenElements) {
		this.roleInstituteBranchModule = roleInstituteBranchModule;
		this.instituteBranchTenureUser = instituteBranchTenureUser;
		this.userRoleScreenElements = userRoleScreenElements;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RoleInstituteBranchModule getRoleInstituteBranchModule() {
		return this.roleInstituteBranchModule;
	}

	public void setRoleInstituteBranchModule(
			RoleInstituteBranchModule roleInstituteBranchModule) {
		this.roleInstituteBranchModule = roleInstituteBranchModule;
	}

	public InstituteBranchTenureUser getInstituteBranchTenureUser() {
		return this.instituteBranchTenureUser;
	}

	public void setInstituteBranchTenureUser(
			InstituteBranchTenureUser instituteBranchTenureUser) {
		this.instituteBranchTenureUser = instituteBranchTenureUser;
	}

	public Set getUserRoleScreenElements() {
		return this.userRoleScreenElements;
	}

	public void setUserRoleScreenElements(Set userRoleScreenElements) {
		this.userRoleScreenElements = userRoleScreenElements;
	}

}
