package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile implements java.io.Serializable {

	private Integer id;
	private UserRoleScreenElement userRoleScreenElement;

	public UserProfile() {
	}

	public UserProfile(UserRoleScreenElement userRoleScreenElement) {
		this.userRoleScreenElement = userRoleScreenElement;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserRoleScreenElement getUserRoleScreenElement() {
		return this.userRoleScreenElement;
	}

	public void setUserRoleScreenElement(
			UserRoleScreenElement userRoleScreenElement) {
		this.userRoleScreenElement = userRoleScreenElement;
	}

}
