package com.ims.security.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private Set instituteBranchTenureUsers = new HashSet(0);

	public Users() {
	}

	public Users(Set instituteBranchTenureUsers) {
		this.instituteBranchTenureUsers = instituteBranchTenureUsers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getInstituteBranchTenureUsers() {
		return this.instituteBranchTenureUsers;
	}

	public void setInstituteBranchTenureUsers(Set instituteBranchTenureUsers) {
		this.instituteBranchTenureUsers = instituteBranchTenureUsers;
	}

}
