package com.ims.academics.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AcademicProgram generated by hbm2java
 */
public class AcademicProgram implements java.io.Serializable {

	private Integer id;
	private Academic academic;
	private Set academicProgramCourses = new HashSet(0);
	private Set instituteBranchAcademicPrograms = new HashSet(0);

	public AcademicProgram() {
	}

	public AcademicProgram(Academic academic) {
		this.academic = academic;
	}

	public AcademicProgram(Academic academic, Set academicProgramCourses,
			Set instituteBranchAcademicPrograms) {
		this.academic = academic;
		this.academicProgramCourses = academicProgramCourses;
		this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Academic getAcademic() {
		return this.academic;
	}

	public void setAcademic(Academic academic) {
		this.academic = academic;
	}

	public Set getAcademicProgramCourses() {
		return this.academicProgramCourses;
	}

	public void setAcademicProgramCourses(Set academicProgramCourses) {
		this.academicProgramCourses = academicProgramCourses;
	}

	public Set getInstituteBranchAcademicPrograms() {
		return this.instituteBranchAcademicPrograms;
	}

	public void setInstituteBranchAcademicPrograms(
			Set instituteBranchAcademicPrograms) {
		this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
	}

}
