package com.ims.academics.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcademicProgram generated by hbm2java
 */
@Entity
@Table(name = "Academic_Program", catalog = "ims2")
public class AcademicProgram implements java.io.Serializable {

	private Integer id;
	private Academic academic;
	private Set academicProgramCourses = new HashSet(0);
	private Set instituteBranchAcademicPrograms = new HashSet(0);

	public AcademicProgram() {
	}

	public AcademicProgram(Academic academic) {
		this.academic = academic;
	}

	public AcademicProgram(Academic academic, Set academicProgramCourses,
			Set instituteBranchAcademicPrograms) {
		this.academic = academic;
		this.academicProgramCourses = academicProgramCourses;
		this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Academic_id", nullable = false)
	public Academic getAcademic() {
		return this.academic;
	}

	public void setAcademic(Academic academic) {
		this.academic = academic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "academicProgram")
	public Set getAcademicProgramCourses() {
		return this.academicProgramCourses;
	}

	public void setAcademicProgramCourses(Set academicProgramCourses) {
		this.academicProgramCourses = academicProgramCourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "academicProgram")
	public Set getInstituteBranchAcademicPrograms() {
		return this.instituteBranchAcademicPrograms;
	}

	public void setInstituteBranchAcademicPrograms(
			Set instituteBranchAcademicPrograms) {
		this.instituteBranchAcademicPrograms = instituteBranchAcademicPrograms;
	}

}
