package com.ims.academics.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AcademicProgramCourse generated by hbm2java
 */
public class AcademicProgramCourse implements java.io.Serializable {

	private Integer id;
	private Course course;
	private AcademicProgram academicProgram;
	private Set tenureAcademicProgramCourses = new HashSet(0);

	public AcademicProgramCourse() {
	}

	public AcademicProgramCourse(Course course, AcademicProgram academicProgram) {
		this.course = course;
		this.academicProgram = academicProgram;
	}

	public AcademicProgramCourse(Course course,
			AcademicProgram academicProgram, Set tenureAcademicProgramCourses) {
		this.course = course;
		this.academicProgram = academicProgram;
		this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public AcademicProgram getAcademicProgram() {
		return this.academicProgram;
	}

	public void setAcademicProgram(AcademicProgram academicProgram) {
		this.academicProgram = academicProgram;
	}

	public Set getTenureAcademicProgramCourses() {
		return this.tenureAcademicProgramCourses;
	}

	public void setTenureAcademicProgramCourses(Set tenureAcademicProgramCourses) {
		this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
	}

}
