package com.ims.academics.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcademicProgramCourse generated by hbm2java
 */
@Entity
@Table(name = "Academic_Program_Course", catalog = "ims2")
public class AcademicProgramCourse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Course course;
	private AcademicProgram academicProgram;
	private Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses = new HashSet<TenureAcademicProgramCourse>(0);

	public AcademicProgramCourse() {
	}

	public AcademicProgramCourse(Course course, AcademicProgram academicProgram) {
		this.course = course;
		this.academicProgram = academicProgram;
	}

	public AcademicProgramCourse(Course course,
			AcademicProgram academicProgram, Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
		this.course = course;
		this.academicProgram = academicProgram;
		this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Academic_Program_id", nullable = false)
	public AcademicProgram getAcademicProgram() {
		return this.academicProgram;
	}

	public void setAcademicProgram(AcademicProgram academicProgram) {
		this.academicProgram = academicProgram;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "academicProgramCourse")
	public Set<TenureAcademicProgramCourse> getTenureAcademicProgramCourses() {
		return this.tenureAcademicProgramCourses;
	}

	public void setTenureAcademicProgramCourses(Set<TenureAcademicProgramCourse> tenureAcademicProgramCourses) {
		this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
	}

}
