package com.ims.academics.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Academic generated by hbm2java
 */
public class Academic implements java.io.Serializable {

	private Integer id;
	private Set academicPrograms = new HashSet(0);

	public Academic() {
	}

	public Academic(Set academicPrograms) {
		this.academicPrograms = academicPrograms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getAcademicPrograms() {
		return this.academicPrograms;
	}

	public void setAcademicPrograms(Set academicPrograms) {
		this.academicPrograms = academicPrograms;
	}

}
