package com.ims.academics.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private Integer id;
	private Set academicProgramCourses = new HashSet(0);

	public Course() {
	}

	public Course(Set academicProgramCourses) {
		this.academicProgramCourses = academicProgramCourses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getAcademicProgramCourses() {
		return this.academicProgramCourses;
	}

	public void setAcademicProgramCourses(Set academicProgramCourses) {
		this.academicProgramCourses = academicProgramCourses;
	}

}
