package com.ims.academics.dal.bean;

import com.ims.core.dal.bean.InstituteBranch;

/**
 * InstituteBranchAcademicProgram generated by hbm2java
 */
public class InstituteBranchAcademicProgram implements java.io.Serializable {

	private Integer id;
	private AcademicProgram academicProgram;
	private InstituteBranch instituteBranch;

	public InstituteBranchAcademicProgram() {
	}

	public InstituteBranchAcademicProgram(AcademicProgram academicProgram,
			InstituteBranch instituteBranch) {
		this.academicProgram = academicProgram;
		this.instituteBranch = instituteBranch;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AcademicProgram getAcademicProgram() {
		return this.academicProgram;
	}

	public void setAcademicProgram(AcademicProgram academicProgram) {
		this.academicProgram = academicProgram;
	}

	public InstituteBranch getInstituteBranch() {
		return this.instituteBranch;
	}

	public void setInstituteBranch(InstituteBranch instituteBranch) {
		this.instituteBranch = instituteBranch;
	}

}
