package com.ims.academics.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.ims.security.dal.bean.InstituteBranchTenureUser;

/**
 * InstituteBranchUserAcademicProgram generated by hbm2java
 */
@Entity
@Table(name = "Institute_Branch_User_Academic_Program", catalog = "ims2")
public class InstituteBranchUserAcademicProgram implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private InstituteBranchTenureUser instituteBranchTenureUser;
	private TenureAcademicProgramCourse tenureAcademicProgramCourse;

	public InstituteBranchUserAcademicProgram() {
	}

	public InstituteBranchUserAcademicProgram(
			InstituteBranchTenureUser instituteBranchTenureUser,
			TenureAcademicProgramCourse tenureAcademicProgramCourse) {
		this.instituteBranchTenureUser = instituteBranchTenureUser;
		this.tenureAcademicProgramCourse = tenureAcademicProgramCourse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Institute_Branch_Tenure_User_id", nullable = false)
	public InstituteBranchTenureUser getInstituteBranchTenureUser() {
		return this.instituteBranchTenureUser;
	}

	public void setInstituteBranchTenureUser(
			InstituteBranchTenureUser instituteBranchTenureUser) {
		this.instituteBranchTenureUser = instituteBranchTenureUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Tenure_Academic_Program_Course_id", nullable = false)
	public TenureAcademicProgramCourse getTenureAcademicProgramCourse() {
		return this.tenureAcademicProgramCourse;
	}

	public void setTenureAcademicProgramCourse(
			TenureAcademicProgramCourse tenureAcademicProgramCourse) {
		this.tenureAcademicProgramCourse = tenureAcademicProgramCourse;
	}

}
