package com.ims.academics.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.ims.core.dal.bean.InstituteBranchTenure;

/**
 * TenureAcademicProgramCourse generated by hbm2java
 */
@Entity
@Table(name = "Tenure_Academic_Program_Course", catalog = "ims2")
public class TenureAcademicProgramCourse implements java.io.Serializable {

	private Integer id;
	private InstituteBranchTenure instituteBranchTenure;
	private AcademicProgramCourse academicProgramCourse;
	private Set instituteBranchUserAcademicPrograms = new HashSet(0);

	public TenureAcademicProgramCourse() {
	}

	public TenureAcademicProgramCourse(
			InstituteBranchTenure instituteBranchTenure,
			AcademicProgramCourse academicProgramCourse) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.academicProgramCourse = academicProgramCourse;
	}

	public TenureAcademicProgramCourse(
			InstituteBranchTenure instituteBranchTenure,
			AcademicProgramCourse academicProgramCourse,
			Set instituteBranchUserAcademicPrograms) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.academicProgramCourse = academicProgramCourse;
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Institute_Branch_Tenure_id", nullable = false)
	public InstituteBranchTenure getInstituteBranchTenure() {
		return this.instituteBranchTenure;
	}

	public void setInstituteBranchTenure(
			InstituteBranchTenure instituteBranchTenure) {
		this.instituteBranchTenure = instituteBranchTenure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Academic_Program_Course_id", nullable = false)
	public AcademicProgramCourse getAcademicProgramCourse() {
		return this.academicProgramCourse;
	}

	public void setAcademicProgramCourse(
			AcademicProgramCourse academicProgramCourse) {
		this.academicProgramCourse = academicProgramCourse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tenureAcademicProgramCourse")
	public Set getInstituteBranchUserAcademicPrograms() {
		return this.instituteBranchUserAcademicPrograms;
	}

	public void setInstituteBranchUserAcademicPrograms(
			Set instituteBranchUserAcademicPrograms) {
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
	}

}
