package com.ims.academics.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.ims.core.dal.bean.InstituteBranchTenure;

/**
 * TenureAcademicProgramCourse generated by hbm2java
 */
public class TenureAcademicProgramCourse implements java.io.Serializable {

	private Integer id;
	private InstituteBranchTenure instituteBranchTenure;
	private AcademicProgramCourse academicProgramCourse;
	private Set instituteBranchUserAcademicPrograms = new HashSet(0);

	public TenureAcademicProgramCourse() {
	}

	public TenureAcademicProgramCourse(
			InstituteBranchTenure instituteBranchTenure,
			AcademicProgramCourse academicProgramCourse) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.academicProgramCourse = academicProgramCourse;
	}

	public TenureAcademicProgramCourse(
			InstituteBranchTenure instituteBranchTenure,
			AcademicProgramCourse academicProgramCourse,
			Set instituteBranchUserAcademicPrograms) {
		this.instituteBranchTenure = instituteBranchTenure;
		this.academicProgramCourse = academicProgramCourse;
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public InstituteBranchTenure getInstituteBranchTenure() {
		return this.instituteBranchTenure;
	}

	public void setInstituteBranchTenure(
			InstituteBranchTenure instituteBranchTenure) {
		this.instituteBranchTenure = instituteBranchTenure;
	}

	public AcademicProgramCourse getAcademicProgramCourse() {
		return this.academicProgramCourse;
	}

	public void setAcademicProgramCourse(
			AcademicProgramCourse academicProgramCourse) {
		this.academicProgramCourse = academicProgramCourse;
	}

	public Set getInstituteBranchUserAcademicPrograms() {
		return this.instituteBranchUserAcademicPrograms;
	}

	public void setInstituteBranchUserAcademicPrograms(
			Set instituteBranchUserAcademicPrograms) {
		this.instituteBranchUserAcademicPrograms = instituteBranchUserAcademicPrograms;
	}

}
