package com.ims.collection.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CollectionSetupData generated by hbm2java
 */
public class CollectionSetupData implements java.io.Serializable {

	private Integer id;
	private CollectionReference collectionReference;
	private DurationType durationType;
	private CollectionType collectionType;
	private Integer collectionReferenceFieldId;
	private Date startDate;
	private Date lastDate;
	private Integer amount;
	private Set collections = new HashSet(0);

	public CollectionSetupData() {
	}

	public CollectionSetupData(CollectionReference collectionReference,
			DurationType durationType, CollectionType collectionType) {
		this.collectionReference = collectionReference;
		this.durationType = durationType;
		this.collectionType = collectionType;
	}

	public CollectionSetupData(CollectionReference collectionReference,
			DurationType durationType, CollectionType collectionType,
			Integer collectionReferenceFieldId, Date startDate, Date lastDate,
			Integer amount, Set collections) {
		this.collectionReference = collectionReference;
		this.durationType = durationType;
		this.collectionType = collectionType;
		this.collectionReferenceFieldId = collectionReferenceFieldId;
		this.startDate = startDate;
		this.lastDate = lastDate;
		this.amount = amount;
		this.collections = collections;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CollectionReference getCollectionReference() {
		return this.collectionReference;
	}

	public void setCollectionReference(CollectionReference collectionReference) {
		this.collectionReference = collectionReference;
	}

	public DurationType getDurationType() {
		return this.durationType;
	}

	public void setDurationType(DurationType durationType) {
		this.durationType = durationType;
	}

	public CollectionType getCollectionType() {
		return this.collectionType;
	}

	public void setCollectionType(CollectionType collectionType) {
		this.collectionType = collectionType;
	}

	public Integer getCollectionReferenceFieldId() {
		return this.collectionReferenceFieldId;
	}

	public void setCollectionReferenceFieldId(Integer collectionReferenceFieldId) {
		this.collectionReferenceFieldId = collectionReferenceFieldId;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(Date lastDate) {
		this.lastDate = lastDate;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Set getCollections() {
		return this.collections;
	}

	public void setCollections(Set collections) {
		this.collections = collections;
	}

}
