package com.ims.collection.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CollectionSetupData generated by hbm2java
 */
@Entity
@Table(name = "Collection_Setup_Data", catalog = "ims2")
public class CollectionSetupData implements java.io.Serializable {

	private Integer id;
	private CollectionReference collectionReference;
	private DurationType durationType;
	private CollectionType collectionType;
	private Integer collectionReferenceFieldId;
	private Date startDate;
	private Date lastDate;
	private Integer amount;
	private Set collections = new HashSet(0);

	public CollectionSetupData() {
	}

	public CollectionSetupData(CollectionReference collectionReference,
			DurationType durationType, CollectionType collectionType) {
		this.collectionReference = collectionReference;
		this.durationType = durationType;
		this.collectionType = collectionType;
	}

	public CollectionSetupData(CollectionReference collectionReference,
			DurationType durationType, CollectionType collectionType,
			Integer collectionReferenceFieldId, Date startDate, Date lastDate,
			Integer amount, Set collections) {
		this.collectionReference = collectionReference;
		this.durationType = durationType;
		this.collectionType = collectionType;
		this.collectionReferenceFieldId = collectionReferenceFieldId;
		this.startDate = startDate;
		this.lastDate = lastDate;
		this.amount = amount;
		this.collections = collections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Collection_Reference_id", nullable = false)
	public CollectionReference getCollectionReference() {
		return this.collectionReference;
	}

	public void setCollectionReference(CollectionReference collectionReference) {
		this.collectionReference = collectionReference;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Duration_Type_id", nullable = false)
	public DurationType getDurationType() {
		return this.durationType;
	}

	public void setDurationType(DurationType durationType) {
		this.durationType = durationType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Collection_Type_id", nullable = false)
	public CollectionType getCollectionType() {
		return this.collectionType;
	}

	public void setCollectionType(CollectionType collectionType) {
		this.collectionType = collectionType;
	}

	@Column(name = "collection_reference_field_id")
	public Integer getCollectionReferenceFieldId() {
		return this.collectionReferenceFieldId;
	}

	public void setCollectionReferenceFieldId(Integer collectionReferenceFieldId) {
		this.collectionReferenceFieldId = collectionReferenceFieldId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_date", length = 10)
	public Date getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(Date lastDate) {
		this.lastDate = lastDate;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collectionSetupData")
	public Set getCollections() {
		return this.collections;
	}

	public void setCollections(Set collections) {
		this.collections = collections;
	}

}
