package com.ims.collection.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.ims.security.dal.bean.InstituteBranchTenureUser;

/**
 * Collection generated by hbm2java
 */
@Entity
@Table(name = "Collection", catalog = "ims2")
public class Collection implements java.io.Serializable {

	private Integer id;
	private DurationType durationType;
	private InstituteBranchTenureUser instituteBranchTenureUser;
	private CollectionSetupData collectionSetupData;
	private CollectionMode collectionMode;
	private CollectionStatus collectionStatus;
	private Set transactions = new HashSet(0);

	public Collection() {
	}

	public Collection(DurationType durationType,
			InstituteBranchTenureUser instituteBranchTenureUser,
			CollectionSetupData collectionSetupData,
			CollectionMode collectionMode, CollectionStatus collectionStatus) {
		this.durationType = durationType;
		this.instituteBranchTenureUser = instituteBranchTenureUser;
		this.collectionSetupData = collectionSetupData;
		this.collectionMode = collectionMode;
		this.collectionStatus = collectionStatus;
	}

	public Collection(DurationType durationType,
			InstituteBranchTenureUser instituteBranchTenureUser,
			CollectionSetupData collectionSetupData,
			CollectionMode collectionMode, CollectionStatus collectionStatus,
			Set transactions) {
		this.durationType = durationType;
		this.instituteBranchTenureUser = instituteBranchTenureUser;
		this.collectionSetupData = collectionSetupData;
		this.collectionMode = collectionMode;
		this.collectionStatus = collectionStatus;
		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Duration_Type_id", nullable = false)
	public DurationType getDurationType() {
		return this.durationType;
	}

	public void setDurationType(DurationType durationType) {
		this.durationType = durationType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Institute_Branch_Tenure_User_id", nullable = false)
	public InstituteBranchTenureUser getInstituteBranchTenureUser() {
		return this.instituteBranchTenureUser;
	}

	public void setInstituteBranchTenureUser(
			InstituteBranchTenureUser instituteBranchTenureUser) {
		this.instituteBranchTenureUser = instituteBranchTenureUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Collection_Setup_Data_id", nullable = false)
	public CollectionSetupData getCollectionSetupData() {
		return this.collectionSetupData;
	}

	public void setCollectionSetupData(CollectionSetupData collectionSetupData) {
		this.collectionSetupData = collectionSetupData;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Collection_Mode_id", nullable = false)
	public CollectionMode getCollectionMode() {
		return this.collectionMode;
	}

	public void setCollectionMode(CollectionMode collectionMode) {
		this.collectionMode = collectionMode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Collection_Status_id", nullable = false)
	public CollectionStatus getCollectionStatus() {
		return this.collectionStatus;
	}

	public void setCollectionStatus(CollectionStatus collectionStatus) {
		this.collectionStatus = collectionStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collection")
	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

}
