package com.ims.collection.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionTypeDetail generated by hbm2java
 */
public class TransactionTypeDetail implements java.io.Serializable {

	private Integer id;
	private TransactionType transactionType;
	private Set transactions = new HashSet(0);

	public TransactionTypeDetail() {
	}

	public TransactionTypeDetail(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	public TransactionTypeDetail(TransactionType transactionType,
			Set transactions) {
		this.transactionType = transactionType;
		this.transactions = transactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

}
