package com.ims.collection.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private Integer id;
	private TransactionTypeDetail transactionTypeDetail;
	private Collection collection;

	public Transaction() {
	}

	public Transaction(TransactionTypeDetail transactionTypeDetail,
			Collection collection) {
		this.transactionTypeDetail = transactionTypeDetail;
		this.collection = collection;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TransactionTypeDetail getTransactionTypeDetail() {
		return this.transactionTypeDetail;
	}

	public void setTransactionTypeDetail(
			TransactionTypeDetail transactionTypeDetail) {
		this.transactionTypeDetail = transactionTypeDetail;
	}

	public Collection getCollection() {
		return this.collection;
	}

	public void setCollection(Collection collection) {
		this.collection = collection;
	}

}
