package com.ims.collection.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType implements java.io.Serializable {

	private Integer id;
	private Set transactionTypeDetails = new HashSet(0);

	public TransactionType() {
	}

	public TransactionType(Set transactionTypeDetails) {
		this.transactionTypeDetails = transactionTypeDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getTransactionTypeDetails() {
		return this.transactionTypeDetails;
	}

	public void setTransactionTypeDetails(Set transactionTypeDetails) {
		this.transactionTypeDetails = transactionTypeDetails;
	}

}
