package com.ims.collection.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "Transaction", catalog = "ims2")
public class Transaction implements java.io.Serializable {

	private Integer id;
	private TransactionTypeDetail transactionTypeDetail;
	private Collection collection;

	public Transaction() {
	}

	public Transaction(TransactionTypeDetail transactionTypeDetail,
			Collection collection) {
		this.transactionTypeDetail = transactionTypeDetail;
		this.collection = collection;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Transaction_Type_Detail_id", nullable = false)
	public TransactionTypeDetail getTransactionTypeDetail() {
		return this.transactionTypeDetail;
	}

	public void setTransactionTypeDetail(
			TransactionTypeDetail transactionTypeDetail) {
		this.transactionTypeDetail = transactionTypeDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Collection_id", nullable = false)
	public Collection getCollection() {
		return this.collection;
	}

	public void setCollection(Collection collection) {
		this.collection = collection;
	}

}
