package com.ims.academics.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "Course", catalog = "ims2")
public class Course implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Set<AcademicProgramCourse> academicProgramCourses = new HashSet<AcademicProgramCourse>(0);

	public Course() {
	}

	public Course(Set<AcademicProgramCourse> academicProgramCourses) {
		this.academicProgramCourses = academicProgramCourses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<AcademicProgramCourse> getAcademicProgramCourses() {
		return this.academicProgramCourses;
	}

	public void setAcademicProgramCourses(Set <AcademicProgramCourse> academicProgramCourses) {
		this.academicProgramCourses = academicProgramCourses;
	}

}
