package com.ims.academics.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.ims.core.dal.bean.InstituteBranch;

/**
 * InstituteBranchAcademicProgram generated by hbm2java
 */
@Entity
@Table(name = "Institute_Branch_Academic_Program", catalog = "ims2")
public class InstituteBranchAcademicProgram implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private AcademicProgram academicProgram;
	private InstituteBranch instituteBranch;

	public InstituteBranchAcademicProgram() {
	}

	public InstituteBranchAcademicProgram(AcademicProgram academicProgram,
			InstituteBranch instituteBranch) {
		this.academicProgram = academicProgram;
		this.instituteBranch = instituteBranch;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Academic_Program_id", nullable = false)
	public AcademicProgram getAcademicProgram() {
		return this.academicProgram;
	}

	public void setAcademicProgram(AcademicProgram academicProgram) {
		this.academicProgram = academicProgram;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Institute_Branch_id", nullable = false)
	public InstituteBranch getInstituteBranch() {
		return this.instituteBranch;
	}

	public void setInstituteBranch(InstituteBranch instituteBranch) {
		this.instituteBranch = instituteBranch;
	}

}
