package com.ims.core.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * InstituteBranchTenure generated by hbm2java
 */
public class InstituteBranchTenure implements java.io.Serializable {

	private Integer id;
	private Tenure tenure;
	private InstituteBranch instituteBranch;
	private Set tenureAcademicProgramCourses = new HashSet(0);
	private Set instituteBranchTenureUsers = new HashSet(0);

	public InstituteBranchTenure() {
	}

	public InstituteBranchTenure(Tenure tenure, InstituteBranch instituteBranch) {
		this.tenure = tenure;
		this.instituteBranch = instituteBranch;
	}

	public InstituteBranchTenure(Tenure tenure,
			InstituteBranch instituteBranch, Set tenureAcademicProgramCourses,
			Set instituteBranchTenureUsers) {
		this.tenure = tenure;
		this.instituteBranch = instituteBranch;
		this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
		this.instituteBranchTenureUsers = instituteBranchTenureUsers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tenure getTenure() {
		return this.tenure;
	}

	public void setTenure(Tenure tenure) {
		this.tenure = tenure;
	}

	public InstituteBranch getInstituteBranch() {
		return this.instituteBranch;
	}

	public void setInstituteBranch(InstituteBranch instituteBranch) {
		this.instituteBranch = instituteBranch;
	}

	public Set getTenureAcademicProgramCourses() {
		return this.tenureAcademicProgramCourses;
	}

	public void setTenureAcademicProgramCourses(Set tenureAcademicProgramCourses) {
		this.tenureAcademicProgramCourses = tenureAcademicProgramCourses;
	}

	public Set getInstituteBranchTenureUsers() {
		return this.instituteBranchTenureUsers;
	}

	public void setInstituteBranchTenureUsers(Set instituteBranchTenureUsers) {
		this.instituteBranchTenureUsers = instituteBranchTenureUsers;
	}

}
