package com.ims.core.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Institute generated by hbm2java
 */
public class Institute implements java.io.Serializable {

	private Integer id;
	private Set instituteBranchs = new HashSet(0);

	public Institute() {
	}

	public Institute(Set instituteBranchs) {
		this.instituteBranchs = instituteBranchs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getInstituteBranchs() {
		return this.instituteBranchs;
	}

	public void setInstituteBranchs(Set instituteBranchs) {
		this.instituteBranchs = instituteBranchs;
	}

}
