package com.ims.core.dal.bean;
// default package
// Generated Jul 15, 2012 5:12:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tenure generated by hbm2java
 */
public class Tenure implements java.io.Serializable {

	private Integer id;
	private Set instituteBranchTenures = new HashSet(0);

	public Tenure() {
	}

	public Tenure(Set instituteBranchTenures) {
		this.instituteBranchTenures = instituteBranchTenures;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getInstituteBranchTenures() {
		return this.instituteBranchTenures;
	}

	public void setInstituteBranchTenures(Set instituteBranchTenures) {
		this.instituteBranchTenures = instituteBranchTenures;
	}

}
