package com.ims.collection.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionTypeDetail generated by hbm2java
 */
@Entity
@Table(name = "Transaction_Type_Detail", catalog = "ims2")
public class TransactionTypeDetail implements java.io.Serializable {

	private Integer id;
	private TransactionType transactionType;
	private Set transactions = new HashSet(0);

	public TransactionTypeDetail() {
	}

	public TransactionTypeDetail(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	public TransactionTypeDetail(TransactionType transactionType,
			Set transactions) {
		this.transactionType = transactionType;
		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Transaction_Type_id", nullable = false)
	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionTypeDetail")
	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

}
