package com.ims.collection.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionType generated by hbm2java
 */
@Entity
@Table(name = "Transaction_Type", catalog = "ims2")
public class TransactionType implements java.io.Serializable {

	private Integer id;
	private Set transactionTypeDetails = new HashSet(0);

	public TransactionType() {
	}

	public TransactionType(Set transactionTypeDetails) {
		this.transactionTypeDetails = transactionTypeDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionType")
	public Set getTransactionTypeDetails() {
		return this.transactionTypeDetails;
	}

	public void setTransactionTypeDetails(Set transactionTypeDetails) {
		this.transactionTypeDetails = transactionTypeDetails;
	}

}
