package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusinessDataReference generated by hbm2java
 */
@Entity
@Table(name = "Business_Data_Reference", catalog = "ims2")
public class BusinessDataReference implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set businessDatas = new HashSet(0);

	public BusinessDataReference() {
	}

	public BusinessDataReference(String name, Set businessDatas) {
		this.name = name;
		this.businessDatas = businessDatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessDataReference")
	public Set getBusinessDatas() {
		return this.businessDatas;
	}

	public void setBusinessDatas(Set businessDatas) {
		this.businessDatas = businessDatas;
	}

}
