package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "Module", catalog = "ims2")
public class Module implements java.io.Serializable {

	private Integer id;
	private Set moduleScreens = new HashSet(0);
	private Set instituteBranchModules = new HashSet(0);

	public Module() {
	}

	public Module(Set moduleScreens, Set instituteBranchModules) {
		this.moduleScreens = moduleScreens;
		this.instituteBranchModules = instituteBranchModules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set getModuleScreens() {
		return this.moduleScreens;
	}

	public void setModuleScreens(Set moduleScreens) {
		this.moduleScreens = moduleScreens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set getInstituteBranchModules() {
		return this.instituteBranchModules;
	}

	public void setInstituteBranchModules(Set instituteBranchModules) {
		this.instituteBranchModules = instituteBranchModules;
	}

}
