package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModuleScreenElement generated by hbm2java
 */
@Entity
@Table(name = "Module_Screen_Element", catalog = "ims2")
public class ModuleScreenElement implements java.io.Serializable {

	private Integer id;
	private BusinessFields businessFields;
	private ModuleScreen moduleScreen;
	private Set userRoleScreenElements = new HashSet(0);

	public ModuleScreenElement() {
	}

	public ModuleScreenElement(BusinessFields businessFields,
			ModuleScreen moduleScreen) {
		this.businessFields = businessFields;
		this.moduleScreen = moduleScreen;
	}

	public ModuleScreenElement(BusinessFields businessFields,
			ModuleScreen moduleScreen, Set userRoleScreenElements) {
		this.businessFields = businessFields;
		this.moduleScreen = moduleScreen;
		this.userRoleScreenElements = userRoleScreenElements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Business_Fields_id", nullable = false)
	public BusinessFields getBusinessFields() {
		return this.businessFields;
	}

	public void setBusinessFields(BusinessFields businessFields) {
		this.businessFields = businessFields;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Module_Screen_id", nullable = false)
	public ModuleScreen getModuleScreen() {
		return this.moduleScreen;
	}

	public void setModuleScreen(ModuleScreen moduleScreen) {
		this.moduleScreen = moduleScreen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moduleScreenElement")
	public Set getUserRoleScreenElements() {
		return this.userRoleScreenElements;
	}

	public void setUserRoleScreenElements(Set userRoleScreenElements) {
		this.userRoleScreenElements = userRoleScreenElements;
	}

}
