package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "Role", catalog = "ims2")
public class Role implements java.io.Serializable {

	private Integer id;
	private RoleType roleType;
	private Set roleInstituteBranchModules = new HashSet(0);

	public Role() {
	}

	public Role(RoleType roleType) {
		this.roleType = roleType;
	}

	public Role(RoleType roleType, Set roleInstituteBranchModules) {
		this.roleType = roleType;
		this.roleInstituteBranchModules = roleInstituteBranchModules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Role_Type_id", nullable = false)
	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set getRoleInstituteBranchModules() {
		return this.roleInstituteBranchModules;
	}

	public void setRoleInstituteBranchModules(Set roleInstituteBranchModules) {
		this.roleInstituteBranchModules = roleInstituteBranchModules;
	}

}
