package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoleInstituteBranchModule generated by hbm2java
 */
@Entity
@Table(name = "Role_Institute_Branch_Module", catalog = "ims2")
public class RoleInstituteBranchModule implements java.io.Serializable {

	private Integer id;
	private Role role;
	private InstituteBranchModule instituteBranchModule;
	private Set userRoleInstituteBranchModules = new HashSet(0);

	public RoleInstituteBranchModule() {
	}

	public RoleInstituteBranchModule(Role role,
			InstituteBranchModule instituteBranchModule) {
		this.role = role;
		this.instituteBranchModule = instituteBranchModule;
	}

	public RoleInstituteBranchModule(Role role,
			InstituteBranchModule instituteBranchModule,
			Set userRoleInstituteBranchModules) {
		this.role = role;
		this.instituteBranchModule = instituteBranchModule;
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Institute_Branch_Module_id", nullable = false)
	public InstituteBranchModule getInstituteBranchModule() {
		return this.instituteBranchModule;
	}

	public void setInstituteBranchModule(
			InstituteBranchModule instituteBranchModule) {
		this.instituteBranchModule = instituteBranchModule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleInstituteBranchModule")
	public Set getUserRoleInstituteBranchModules() {
		return this.userRoleInstituteBranchModules;
	}

	public void setUserRoleInstituteBranchModules(
			Set userRoleInstituteBranchModules) {
		this.userRoleInstituteBranchModules = userRoleInstituteBranchModules;
	}

}
