package com.ims.security.dal.bean;
// default package
// Generated Jul 21, 2012 4:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRoleScreenElement generated by hbm2java
 */
@Entity
@Table(name = "User_Role_Screen_Element", catalog = "ims2")
public class UserRoleScreenElement implements java.io.Serializable {

	private Integer id;
	private UserRoleInstituteBranchModule userRoleInstituteBranchModule;
	private Permission permission;
	private Rule rule;
	private ModuleScreenElement moduleScreenElement;
	private Set userProfiles = new HashSet(0);
	private Set businessDatas = new HashSet(0);

	public UserRoleScreenElement() {
	}

	public UserRoleScreenElement(
			UserRoleInstituteBranchModule userRoleInstituteBranchModule,
			Permission permission, Rule rule,
			ModuleScreenElement moduleScreenElement) {
		this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
		this.permission = permission;
		this.rule = rule;
		this.moduleScreenElement = moduleScreenElement;
	}

	public UserRoleScreenElement(
			UserRoleInstituteBranchModule userRoleInstituteBranchModule,
			Permission permission, Rule rule,
			ModuleScreenElement moduleScreenElement, Set userProfiles,
			Set businessDatas) {
		this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
		this.permission = permission;
		this.rule = rule;
		this.moduleScreenElement = moduleScreenElement;
		this.userProfiles = userProfiles;
		this.businessDatas = businessDatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_Role_Institute_Branch_Module_id", nullable = false)
	public UserRoleInstituteBranchModule getUserRoleInstituteBranchModule() {
		return this.userRoleInstituteBranchModule;
	}

	public void setUserRoleInstituteBranchModule(
			UserRoleInstituteBranchModule userRoleInstituteBranchModule) {
		this.userRoleInstituteBranchModule = userRoleInstituteBranchModule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Permission_id", nullable = false)
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Rule_id", nullable = false)
	public Rule getRule() {
		return this.rule;
	}

	public void setRule(Rule rule) {
		this.rule = rule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Module_Screen_Element_id", nullable = false)
	public ModuleScreenElement getModuleScreenElement() {
		return this.moduleScreenElement;
	}

	public void setModuleScreenElement(ModuleScreenElement moduleScreenElement) {
		this.moduleScreenElement = moduleScreenElement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoleScreenElement")
	public Set getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set userProfiles) {
		this.userProfiles = userProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoleScreenElement")
	public Set getBusinessDatas() {
		return this.businessDatas;
	}

	public void setBusinessDatas(Set businessDatas) {
		this.businessDatas = businessDatas;
	}

}
